name: 📝 Content Request
description: Запросить детальный контент для темы
title: "[CONTENT] "
labels: ["content", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        У нас есть структура из 85+ тем, но многим нужен детальный контент! 📚
        
  - type: dropdown
    id: file
    attributes:
      label: 📝 Для какой темы нужен контент?
      description: Выбери тему или напиши свою
      options:
        - technologies/Linux.md
        - technologies/Docker.md
        - technologies/Kubernetes.md
        - technologies/Windows Server.md
        - technologies/Active Directory.md
        - technologies/Ansible.md
        - technologies/Terraform.md
        - technologies/AWS.md
        - technologies/Azure.md
        - technologies/Prometheus.md
        - technologies/PostgreSQL.md
        - Другая (укажу в описании)
    validations:
      required: true
      
  - type: textarea
    id: custom-topic
    attributes:
      label: 📌 Другая тема (если выбрал "Другая")
      placeholder: Укажи путь к файлу, например technologies/Redis.md
      
  - type: checkboxes
    id: what-needed
    attributes:
      label: 🎯 Что нужно добавить?
      options:
        - label: Практические примеры команд/кода
        - label: Best practices и рекомендации
        - label: Troubleshooting секция
        - label: Ресурсы для изучения (книги, курсы)
        - label: Типичные ошибки
        - label: Задачи для самопроверки
        - label: Весь контент по template
          
  - type: textarea
    id: details
    attributes:
      label: 💡 Дополнительная информация
      description: Что конкретно хотелось бы видеть?
      placeholder: |
        Например:
        - Хочу примеры Dockerfile для разных языков
        - Нужны команды для troubleshooting
        - Хочу понять отличия от аналогов
      
  - type: checkboxes
    id: help
    attributes:
      label: ✋ Готов помочь?
      options:
        - label: Я могу написать этот контент сам и создать PR
        - label: Могу помочь с review контента
