name: 💡 New Technology
description: Предложить добавить новую технологию в roadmap
title: "[NEW] "
labels: ["enhancement", "new-topic"]
body:
  - type: markdown
    attributes:
      value: |
        Считаешь что какая-то технология должна быть в roadmap? 🚀
        
  - type: input
    id: technology
    attributes:
      label: 💡 Название технологии
      placeholder: Например, "GitLab Runner" или "Podman"
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: 📁 Категория
      description: Куда относится эта технология?
      options:
        - Операционные системы
        - Microsoft экосистема
        - Сети
        - Виртуализация и контейнеризация
        - Автоматизация
        - Мониторинг
        - Базы данных
        - Безопасность
        - Облачные технологии
        - DevOps
        - Веб-серверы
        - Хранилища данных
        - Практики
        - Другое
    validations:
      required: true
      
  - type: textarea
    id: why-important
    attributes:
      label: 🎯 Почему это важно для roadmap?
      description: Объясни зачем системному администратору эта технология
      placeholder: |
        Например:
        - Активно используется в production
        - Заменяет устаревшие решения
        - Стандарт индустрии
        - Набирает популярность
    validations:
      required: true
      
  - type: checkboxes
    id: level
    attributes:
      label: 📊 На каком уровне должна быть?
      description: Можно выбрать несколько
      options:
        - label: Junior SysAdmin
        - label: Middle SysAdmin
        - label: Senior SysAdmin
          
  - type: textarea
    id: related
    attributes:
      label: 🔗 Связи с другими темами
      description: С чем эта технология связана?
      placeholder: |
        Например:
        - Требует знания: Docker, Linux
        - Альтернатива: Docker
        - Используется вместе с: Kubernetes
        
  - type: textarea
    id: resources
    attributes:
      label: 📚 Ресурсы для изучения
      description: Знаешь хорошие источники по этой теме?
      placeholder: |
        - Официальная документация: URL
        - Книга: "Название"
        - Курс: Название
      
  - type: checkboxes
    id: help
    attributes:
      label: ✋ Готов написать контент?
      options:
        - label: Да, я могу написать детальный контент используя template
        - label: Нет, только предложение
